import db
db.Town(name='Комсомольск-на-Амуре', description='Город в Хабаровском крае России').save()
db.Town(name='Новосибирск', description='Город в Новосибирской области России').save()
db.Town(name='Академгородок', description='Академовцы искренне верят что они отдельный населённый пункт, а не часть Новосибирска').save()
db.Town(name='Санкт-Петербург', description='Какой-то город России').save()
db.Town(name='Москва', description='Какой-то город не-России').save()

db.PointOfInterest(title='Авиастроительный завод', description='Завод - это судьба. А авиастроительный - в комсе', coordinates=(50.59702, 137.069733), town=db.Town.objects(name='Комсомольск-на-Амуре')[0]).save()
db.PointOfInterest(title='Парк Культуры им.Гагарина', description='Это действительно парк', coordinates=(50.580203, 137.073218), town=db.Town.objects(name='Комсомольск-на-Амуре')[0]).save()
db.PointOfInterest(title='Авиастроительный завод2', description='Тут нет второго завода, но надо вкинуть данные', coordinates=(50.59702, 137.069733), town=db.Town.objects(name='Комсомольск-на-Амуре')[0]).save()
db.PointOfInterest(title='Новосибирская точка', description='Не знаю, не был там', coordinates=(55.040266, 82.960055), town=db.Town.objects(name='Новосибирск')[0]).save()
db.PointOfInterest(title='НГУ', description='Вуз мира', coordinates=(54.843072, 83.090792), town=db.Town.objects(name='Академгородок')[0]).save()
db.PointOfInterest(title='СУНЦ НГУ', description='Школа мира', coordinates=(54.84536, 83.094595), town=db.Town.objects(name='Академгородок')[0]).save()
db.PointOfInterest(title='ИТМО ломо', description='... и я не могу их осуждать. Но хотя осуждаю', coordinates=(59.926835, 30.337795), town=db.Town.objects(name='Санкт-Петербург')[0]).save()
db.PointOfInterest(title='ИТМО гк', description='кт итмо кт итмо кт итмо', coordinates=(59.957238, 30.308108), town=db.Town.objects(name='Санкт-Петербург')[0]).save()
db.PointOfInterest(title='ИТМО вязьма', description='Я действительно здесь живу', coordinates=(59.972629, 30.302593), town=db.Town.objects(name='Санкт-Петербург')[0]).save()
db.PointOfInterest(title='ИТМО чайка', description='Когда-нибудь Чернышевская откроется', coordinates=(59.946456, 30.345535), town=db.Town.objects(name='Санкт-Петербург')[0]).save()
db.PointOfInterest(title='Главное здание МГУ', description='Вышка украла шпиль...', coordinates=(55.702567, 37.531598), town=db.Town.objects(name='Москва')[0]).save()
db.PointOfInterest(title='ДСЛ МГУ', description='Всего два года...', coordinates=(55.696264, 37.513474), town=db.Town.objects(name='Москва')[0]).save()
db.PointOfInterest(title='ВДНХ', description='Так красиво, наверное', coordinates=(55.825101, 37.641881), town=db.Town.objects(name='Москва')[0]).save()

db.Tag(name='Вуз').save()
db.Tag(name='Проживание').save()
db.Tag(name='Отдых').save()
db.Tag(name='Образование').save()
db.Tag(name='Завод').save()
db.Tag(name='Парк').save()
db.Tag(name='Культура').save()
db.Tag(name='Разное').save()
db.Tag(name='спам1').save()
db.Tag(name='спам2').save()
db.Tag(name='спам3').save()
db.Tag(name='спам4').save()
db.Tag(name='спам5').save()

db.PointTag(point=db.PointOfInterest.objects(title='Авиастроительный завод')[0], tag=db.Tag.objects(name='Завод')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='Парк Культуры им.Гагарина')[0], tag=db.Tag.objects(name='Парк')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='Парк Культуры им.Гагарина')[0], tag=db.Tag.objects(name='Отдых')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='Парк Культуры им.Гагарина')[0], tag=db.Tag.objects(name='Культура')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='Авиастроительный завод2')[0], tag=db.Tag.objects(name='Завод')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='Новосибирская точка')[0], tag=db.Tag.objects(name='Разное')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='НГУ')[0], tag=db.Tag.objects(name='Вуз')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='НГУ')[0], tag=db.Tag.objects(name='Образование')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='СУНЦ НГУ')[0], tag=db.Tag.objects(name='Образование')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='ИТМО ломо')[0], tag=db.Tag.objects(name='Вуз')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='ИТМО ломо')[0], tag=db.Tag.objects(name='Образование')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='ИТМО гк')[0], tag=db.Tag.objects(name='Вуз')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='ИТМО гк')[0], tag=db.Tag.objects(name='Образование')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='ИТМО вязьма')[0], tag=db.Tag.objects(name='Проживание')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='ИТМО вязьма')[0], tag=db.Tag.objects(name='Вуз')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='ИТМО чайка')[0], tag=db.Tag.objects(name='Вуз')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='ИТМО чайка')[0], tag=db.Tag.objects(name='Образование')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='Главное здание МГУ')[0], tag=db.Tag.objects(name='Вуз')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='Главное здание МГУ')[0], tag=db.Tag.objects(name='Проживание')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='ДСЛ МГУ')[0], tag=db.Tag.objects(name='Вуз')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='ДСЛ МГУ')[0], tag=db.Tag.objects(name='Проживание')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='ВДНХ')[0], tag=db.Tag.objects(name='Отдых')[0]).save()
db.PointTag(point=db.PointOfInterest.objects(title='ВДНХ')[0], tag=db.Tag.objects(name='Культура')[0]).save()

db.User(nickname='Steve1', email='SteveStevenson1@gmail.com').save()
db.User(nickname='Steve2', email='SteveStevenson2@gmail.com').save()
db.User(nickname='Steve3', email='SteveStevenson3@gmail.com').save()
db.User(nickname='Steve4', email='SteveStevenson4@gmail.com').save()
db.User(nickname='Steve5', email='SteveStevenson5@gmail.com').save()
db.User(nickname='Steve6', email='SteveStevenson6@gmail.com').save()
db.User(nickname='Steve7', email='SteveStevenson7@gmail.com').save()
db.User(nickname='Steve8', email='SteveStevenson8@gmail.com').save()
db.User(nickname='Steve9', email='SteveStevenson9@gmail.com').save()
db.User(nickname='Steve10', email='SteveStevenson10@gmail.com').save()
db.User(nickname='Steve11', email='SteveStevenson11@gmail.com').save()
db.User(nickname='Steve12', email='SteveStevenson12@gmail.com').save()